blank_issues_enabled: false
contact_links:
  - name: Need help with a guide or wish to discuss a privacy or security topic?
    url: https://github.com/sunknudsen/guides/discussions
    about: Please use discussions
